
@token = token
### Create Proprietário
POST http://localhost:3000/proprietario/create
Content-Type: application/json
x-access-token: {{token}}
 
{
    "cpf": "12345678901",
    "nome": "João Silva",
    "fone": "47999857254"
}
 
### Load All Proprietários
GET http://localhost:3000/proprietario/loadAll
x-access-token: {{token}}
 
### Delete Proprietário
DELETE http://localhost:3000/proprietario/delete
Content-Type: application/json
x-access-token: {{token}}
 
{
    "cpf": "12345678901"
}