@token = coloque o token aqui
### Create Veículo
POST http://localhost:3000/veiculo/create
Content-Type: application/json
x-access-token: {{token}}
 
{
    "placa_veiculo": "ABC-123",
    "modelo_veiculo": "Fusca",
    "marca": "Volkswagen",
    "ano": 1970,
    "proprietario": "12345678901",
    "preco_veiculo": 50000
}
 
### Load All Veículos
GET http://localhost:3000/veiculo/loadAll
x-access-token: {{token}}
 
### Load Veículo by Proprietário
POST http://localhost:3000/veiculo/loadByP
Content-Type: application/json
x-access-token: {{token}}
 
{
    "cpf": "12345678901"
}
 
### Load Veículo by Tipo
POST http://localhost:3000/veiculo/loadByTipo
Content-Type: application/json
x-access-token: {{token}}
 
{
    "tipo": "2"
}
 

### Delete Veículo
DELETE http://localhost:3000/veiculo/delete
Content-Type: application/json
x-access-token: {{token}}
 
{
    "placa": "ABC-1234"
}